; BLINK EXAMPLE: LED ON PIN RD3 CHANGE IT STATES AFTER SOME DELAY TIME
; (WE DO NOT USE INTERRUPT IN THIS CODE)
; FELLIPE LEANDRO - 05/07/2019
    
; TODO INSERT CONFIG CODE HERE USING CONFIG BITS GENERATOR
#include <p18f4550.inc>
#include "config_bits.inc"
  

    
N_OV    EQU 0x3d
UDATA
COUNT_OV    RES 1 
org 0x00          ; processor reset vector
    GOTO    START                   ; go to beginning of program

; TODO ADD INTERRUPTS HERE IF USED


org 0x20
START
 banksel COUNT_OV 
 MOVLW	N_OV
 MOVWF	COUNT_OV
 ;Configure LED PINS
 BANKSEL    TRISD
 CLRF	    TRISD
 BCF	    TRISD,RD3 ; PINO COMO SAIDA
 BANKSEL    PORTD
 MOVLW	    0XFF
 MOvwf	    PORTD
 BSF	    PORTD,RD3 ; LED É ATIVO BAIXO
 ;CONFIGURAR TEMPORIZADOR
 BANKSEL    T0CON
 BCF	    T0CON,TMR0ON    ;STOP TIMER0
 BCF	    T0CON,T0CS	    ; CLOCK SOURCE: INTERNAL CYCLE
 BCF	    T0CON,PSA	    ; USE PRESCALER
 BSF	    T0CON,T0PS2	    ;PRESCALER: 1/32
 BSF	    T0CON,T0PS1
 BCF	    T0CON,T0PS0
 BANKSEL    INTCON
 BCF	    INTCON,TMR0IF   ;CLEAR OVERFLOW FLAG
 BSF	    T0CON,TMR0ON    ;TURN ON TIMER0
 LOOP
 ;CHANGE LED PIN STATE
 MOVLW	    0X08    ; only bit 3 as '1'
 XORWF	    PORTD,f ;XOR REGISTER WITH W AND STORE IN REGISTER
 ; WAIT 1 SECOND
 CALL	    _DELAY
 GOTO LOOP
 
 _DELAY
    BANKSEL COUNT_OV
    MOVLW   N_OV
    MOVWF   COUNT_OV
    START_TIMER
	MOVLW   0X00
	BANKSEL TMR0
	MOVWF   TMR0
	TEST_TIMER
	BTFSS   INTCON,TMR0IF   ;OVERFLOW OCCURRED?
	GOTO    TEST_TIMER
	BCF	INTCON,TMR0IF	;CLEAR FLAG
	BANKSEL COUNT_OV
	DECFSZ  COUNT_OV
	GOTO	START_TIMER
	RETURN
 
 END